pipeline
{
    agent any
    stages
    {
        #stage("Run py app")
        #{
        #    steps
        #    {
        #        echo "========executing Python application========"
        #        sh "./sq.py"
        #    }
        #}
        #stage("Create nginx docker image with generated image by py app")
        #{
        #    steps
        #    {
        #        echo "========building Docker image========"
        #        dir('content')
        #        {
        #            sh "docker build -t pyweb:1.0 -f ../docker/Dockerfile ."
        #            sh "docker images"
        #        }
        #    }
        #}
	stage("Check connect")
        {
            steps
            {
                echo "========Check========"
                sh "ls -la"
            }
        }	
    }
}
