pipeline
{
    agent any
    stages
    {
        stage("Build nginx container")
        {
            steps
            {
                echo "======== Start building nginx container ========"
                dir('content')
                {
                    sh "docker build -t ngixn_on_vds:v1.0 -f ../docker/Dockerfile ."
                    sh "docker run -d -p 80:80 ngixn_on_vds:v1.0"
                }
            }
        }
    }
}
